# Basic version of an "automated" tooltip generator for authors, posts, pages.
# Copy either of the following strings if you want to add a new tooltip.
#
# External link with tooltip:
# SHORTCUT: <a href="https://shadowlands.wowhead.com/TYPE=ID" target="blank">PLAIN_NAME</a>
#
# Non-external link but with wowhead icon next to the tooltip:
# SHORTCUT: <a href="#" data-wowhead="TYPE=ID">PLAIN_NAME</a>
#
# Replace SHORTCUT    with the name you want
# Replace TYPE        with "spell" or "item"
# Replace ID          with the appropriate id
# Replace PLAIN_NAME  with the appropriate base name

# Spec Tree

aftershock: <a href="https://www.wowhead.com/spell=273221" target="blank">Aftershock</a>
afs: <a href="https://www.wowhead.com/spell=273221" target="blank">Aftershock</a>

ancestral_wolf_affinity: <a href="https://www.wowhead.com/spell=382197/ancestral-wolf-affinity" target="blank">Ancestral Wolf Affinity</a>
awa: <a href="https://www.wowhead.com/spell=382197/ancestral-wolf-affinity" target="blank">Ancestral Wolf Affinity</a>

ascendance: <a href="https://www.wowhead.com/spell=114050" target="blank">Ascendance</a>
asc: <a href="https://www.wowhead.com/spell=114050" target="blank">Ascendance</a>

call_of_fire: <a href="https://www.wowhead.com/spell=378255/call-of-fire" target="blank">Call of Fire</a>

call_of_thunder: <a href="https://www.wowhead.com/spell=378241/call-of-thunder" target="blank">Call of Thunder</a>

deeply_rooted_elements: <a href="https://www.wowhead.com/spell=378270/deeply-rooted-elements" target="blank">Deeply Rooted Elements</a>
dre: <a href="https://www.wowhead.com/spell=378270/deeply-rooted-elements" target="blank">Deeply Rooted Elements</a>

echo_chamber: <a href="https://www.wowhead.com/spell=382032/echo-chamber" target="blank">Echo Chamber</a>

echoes_of_great_sundering: <a href="https://www.wowhead.com/spell=384087/echoes-of-great-sundering" target="blank">Echoes of Great Sundering</a>
eogs: <a href="https://www.wowhead.com/spell=384087/echoes-of-great-sundering" target="blank">Echoes of Great Sundering</a>

echo_of_the_elements: <a href="https://www.wowhead.com/spell=333919/echo-of-the-elements" target="blank">Echo of the Elements</a>
eote: <a href="https://www.wowhead.com/spell=333919/echo-of-the-elements" target="blank">Echo of the Elements</a>
echo: <a href="https://www.wowhead.com/spell=333919/echo-of-the-elements" target="blank">Echo of the Elements</a>

electrified_shocks: <a href="https://www.wowhead.com/spell=382086/electrified-shocks" target="blank">Electrified Shocks</a>
e_shocks: <a href="https://www.wowhead.com/spell=382086/electrified-shocks" target="blank">Electrified Shocks</a>

elemental_blast: <a href="https://www.wowhead.com/spell=117014" target="blank">Elemental Blast</a>
eb: <a href="https://www.wowhead.com/spell=117014" target="blank">Elemental Blast</a>

elemental_equilibrium: <a href="https://www.wowhead.com/spell=378271/elemental-equilibrium" target="blank">Elemental Equilibrium</a>
eeq: <a href="https://www.wowhead.com/spell=378271/elemental-equilibrium" target="blank">Elemental Equilibrium</a>

eye_of_the_storm: <a href="https://www.wowhead.com/spell=381708/eye-of-the-storm" target="blank">Eye of the Storm</a>
eots: <a href="https://www.wowhead.com/spell=381708/eye-of-the-storm" target="blank">Eye of the Storm</a>

fire_elemental: <a href="https://www.wowhead.com/spell=198067" target="blank">Fire Elemental</a>
fe: <a href="https://www.wowhead.com/spell=198067" target="blank">Fire Elemental</a>

flames_of_the_cauldron: <a href="https://www.wowhead.com/spell=378266/flames-of-the-cauldron" target="blank">Flames of the Cauldron</a>

flash_of_lightning: <a href="https://www.wowhead.com/spell=381936/flash-of-lightning" target="blank">Flash of Lightning</a>
fol: <a href="https://www.wowhead.com/spell=381936/flash-of-lightning" target="blank">Flash of Lightning</a>

flow_of_power: <a href="https://www.wowhead.com/spell=385923/flow-of-power" target="blank">Flow of Power</a>

flux_melting: <a href="https://www.wowhead.com/spell=381776/flux-melting" target="blank">Flux Melting</a>
fm: <a href="https://www.wowhead.com/spell=381776/flux-melting" target="blank">Flux Melting</a>

further_beyond: <a href="https://www.wowhead.com/spell=381787/further-beyond" target="blank">Further Beyond</a>
fb: <a href="https://www.wowhead.com/spell=381787/further-beyond" target="blank">Further Beyond</a>

icefury: <a href="https://www.wowhead.com/spell=210714" target="blank">Icefury</a>
if: <a href="https://www.wowhead.com/spell=210714" target="blank">Icefury</a>

imp_flametongue_weapon: <a href="https://www.wowhead.com/spell=382027/improved-flametongue-weapon" target="blank">Improved Flametongue Weapon</a>
imp_ftw: <a href="https://www.wowhead.com/spell=382027/improved-flametongue-weapon" target="blank">Improved Flametongue Weapon</a>

inundate: <a href="https://www.wowhead.com/spell=378776/inundate" target="blank">Inundate</a>

lava_surge: <a href="https://www.wowhead.com/spell=77756" target="blank">Lava Surge</a>
lvs: <a href="https://www.wowhead.com/spell=77756" target="blank">Lava Surge</a>

lightning_rod: <a href="https://www.wowhead.com/spell=210689/lightning-rod" target="blank">Lightning Rod</a>
lr: <a href="https://www.wowhead.com/spell=210689/lightning-rod" target="blank">Lightning Rod</a>

liquid_magma_totem: <a href="https://www.wowhead.com/spell=192222" target="blank">Liquid Magma Totem</a>
lmt: <a href="https://www.wowhead.com/spell=192222" target="blank">Liquid Magma Totem</a>

master_of_the_elements: <a href="https://www.wowhead.com/spell=16166" target="blank">Master of the Elements</a>
mote: <a href="https://www.wowhead.com/spell=16166" target="blank">Master of the Elements</a>

magma_chamber: <a href="https://www.wowhead.com/spell=381932/magma-chamber" target="blank">Magma Chamber</a>

mountains_will_fall: <a href="https://www.wowhead.com/spell=381726/mountains-will-fall" target="blank">Mountains Will Fall</a>
mwf: <a href="https://www.wowhead.com/spell=381726/mountains-will-fall" target="blank">Mountains Will Fall</a>

oath_of_the_far_seer: <a href="https://www.wowhead.com/spell=381785/oath-of-the-far-seer" target="blank">Oath of the Far Seer</a>
ootfs: <a href="https://www.wowhead.com/spell=381785/oath-of-the-far-seer" target="blank">Oath of the Far Seer</a>

power_of_the_maelstrom: <a href="https://www.wowhead.com/spell=191861/power-of-the-maelstrom" target="blank">Power of the Maelstrom</a>
potm: <a href="https://www.wowhead.com/spell=191861/power-of-the-maelstrom" target="blank">Power of the Maelstrom</a>

primal_elementalist: <a href="https://www.wowhead.com/spell=117013" target="blank">Primal Elementalist</a>
pe: <a href="https://www.wowhead.com/spell=117013" target="blank">Primal Elementalist</a>

primordial_bond: <a href="https://www.wowhead.com/spell=381764/primordial-bond" target="blank">Primordial Bond</a>

primordial_fury: <a href="https://www.wowhead.com/spell=378193/primordial-fury" target="blank">Primordial Fury</a>

primordial_surge: <a href="https://www.wowhead.com/spell=386474/primordial-surge" target="blank">Primordial Surge</a>
ps: <a href="https://www.wowhead.com/spell=386474/primordial-surge" target="blank">Primordial Surge</a>

primordial wave: <a href="https://www.wowhead.com/spell=375982/primordial-wave" target="blank">Primordial Wave</a>
pw: <a href="https://www.wowhead.com/spell=375982/primordial-wave" target="blank">Primordial Wave</a>

refreshing_waters: <a href="https://www.wowhead.com/spell=378211/refreshing-waters" target="blank">Refreshing Waters</a>

rolling_magma: <a href="https://www.wowhead.com/spell=386443/rolling-magma" target="blank">Rolling Magma</a>

searing_flames: <a href="https://www.wowhead.com/spell=381782/searing-flames" target="blank">Searing Flames</a>
sf: <a href="https://www.wowhead.com/spell=381782/searing-flames" target="blank">Searing Flames</a>

skybreakers_fiery_demise: <a href="https://www.wowhead.com/spell=378310/skybreakers-fiery-demise" target="blank">Skybreaker's Fiery Demise</a>
sfd: <a href="https://www.wowhead.com/spell=378310/skybreakers-fiery-demise" target="blank">Skybreaker's Fiery Demise</a>
skyb: <a href="https://www.wowhead.com/spell=378310/skybreakers-fiery-demise" target="blank">Skybreaker's Fiery Demise</a>

splintered_elements: <a href="https://www.wowhead.com/spell=382042/splintered-elements" target="blank">Splintered Elements</a>
splinter: <a href="https://www.wowhead.com/spell=382042/splintered-elements" target="blank">Splintered Elements</a>

storm_elemental: <a href="https://www.wowhead.com/spell=192249" target="blank">Storm Elemental</a>
se: <a href="https://www.wowhead.com/spell=192249" target="blank">Storm Elemental</a>

stormkeeper: <a href="https://www.wowhead.com/spell=191634" target="blank">Stormkeeper</a>
sk: <a href="https://www.wowhead.com/spell=191634" target="blank">Stormkeeper</a>

surge_of_power: <a href="https://www.wowhead.com/spell=262303/surge-of-power" target="blank">Surge of Power</a>
sop: <a href="https://www.wowhead.com/spell=262303/surge-of-power" target="blank">Surge of Power</a>

swelling_maelstrom: <a href="https://www.wowhead.com/spell=381707/swelling-maelstrom" target="blank">Swelling Maelstrom</a>

tumultuous_fissures: <a href="https://www.wowhead.com/spell=381743/tumultuous-fissures" target="blank">Tumultuous Fissures</a>

unrelenting_calamity: <a href="https://www.wowhead.com/spell=382685/unrelenting-calamity" target="blank">Unrelenting Calamity</a>

windspeakers_lava_resurgence: <a href="https://www.wowhead.com/spell=378268/windspeakers-lava-resurgence" target="blank">Windspeaker's Lava Resurgence</a>
ws: <a href="https://www.wowhead.com/spell=378268/windspeakers-lava-resurgence" target="blank">Windspeaker's Lava Resurgence</a>
wlr: <a href="https://www.wowhead.com/spell=378268/windspeakers-lava-resurgence" target="blank">Windspeaker's Lava Resurgence</a>

# Class Tree
ancestral_defense: <a href="https://www.wowhead.com/spell=382947/ancestral-defense" target="blank">Ancestral Defense</a>
ancestral_defence: <a href="https://www.wowhead.com/spell=382947/ancestral-defense" target="blank">Ancestral Defense</a>

ancestral_guidance: <a href="https://www.wowhead.com/spell=108281" target="blank">Ancestral Guidance</a>
ag: <a href="https://www.wowhead.com/spell=108281" target="blank">Ancestral Guidance</a>

astral_bulwark: <a href="https://www.wowhead.com/spell=377933/astral-bulwark" target="blank">Astral Bulwark</a>

astral_shift: <a href="https://www.wowhead.com/spell=108271" target="blank">Astral Shift</a>
as: <a href="https://www.wowhead.com/spell=108271" target="blank">Astral Shift</a>

brimming_with_life: <a href="https://www.wowhead.com/spell=381689/brimming-with-life" target="blank">Brimming with Life</a>

call_of_the_elements: <a href="https://www.wowhead.com/spell=383011/call-of-the-elements" target="blank">Call of the Elements</a>
cote: <a href="https://www.wowhead.com/spell=383011/call-of-the-elements" target="blank">Call of the Elements</a>

capacitor_totem: <a href="https://www.wowhead.com/spell=192058" target="blank">Capacitor Totem</a>

chain_heal: <a href="https://www.wowhead.com/spell=1064" target="blank">Chain Heal</a>

cleanse_spirit: <a href="https://www.wowhead.com/spell=51886" target="blank">Cleanse Spirit</a>

creation_core: <a href="https://www.wowhead.com/spell=383012/creation-core" target="blank">Creation Core</a>

earthgrab_totem: <a href="https://www.wowhead.com/spell=51485/earthgrab-totem" target="blank">Earthgrab Totem</a>

earth_elemental: <a href="https://www.wowhead.com/spell=198103" target="blank">Earth Elemental</a>
ee: <a href="https://www.wowhead.com/spell=198103" target="blank">Earth Elemental</a>

earth_shield: <a href="https://www.wowhead.com/spell=974" target="blank">Earth Shield</a>

elemental_orbit: <a href="https://www.wowhead.com/spell=383010/elemental-orbit" target="blank">Elemental Orbit</a>

elemental_warding: <a href="https://www.wowhead.com/spell=381650/elemental-warding" target="blank">Elemental Warding</a>

enfeeblement: <a href="https://www.wowhead.com/spell=378079/enfeeblement" target="blank">Enfeeblement</a>

fire_and_ice: <a href="https://www.wowhead.com/spell=382886/fire-and-ice" target="blank">Fire and Ice</a>

flurry: <a href="https://www.wowhead.com/spell=382888/flurry" target="blank">Flurry</a>

focused_insight: <a href="https://www.wowhead.com/spell=381666/focused-insight" target="blank">Focused Insight</a>

go_with_the_flow: <a href="https://www.wowhead.com/spell=381678/go-with-the-flow" target="blank">Go with the Flow</a>

graceful_spirit: <a href="https://www.wowhead.com/spell=192088/graceful-spirit" target="blank">Graceful Spirit</a>

greater_purge: <a href="https://www.wowhead.com/spell=378773/greater-purge" target="blank">Greater Purge</a>

guardians_cudgel: <a href="https://www.wowhead.com/spell=381819/guardians-cudgel" target="blank">Guardian's Cudgel</a>

gust_of_wind: <a href="https://www.wowhead.com/spell=192063/gust-of-wind" target="blank">Gust of Wind</a>
gow: <a href="https://www.wowhead.com/spell=192063/gust-of-wind" target="blank">Gust of Wind</a>

healing_stream_totem: <a href="https://www.wowhead.com/spell=5394" target="blank">Healing Stream Totem</a>
hst: <a href="https://www.wowhead.com/spell=5394" target="blank">Healing Stream Totem</a>

hex: <a href="https://www.wowhead.com/spell=51514" target="blank">Hex</a>

imp_lightning_bolt: <a href="https://www.wowhead.com/spell=381674/improved-lightning-bolt" target="blank">Improved Lightning Bolt</a>

lightning_lasso: <a href="https://www.wowhead.com/spell=305483/lightning-lasso" target="blank">Lightning Lasso</a>

maelstrom_weapon: <a href="https://www.wowhead.com/spell=187880/maelstrom-weapon" target="blank">Maelstrom Weapon</a>
msw: <a href="https://www.wowhead.com/spell=187880/maelstrom-weapon" target="blank">Maelstrom Weapon</a>

mana_spring: <a href="https://www.wowhead.com/spell=381930/mana-spring-totem" target="blank">Mana Spring</a>
ms: <a href="https://www.wowhead.com/spell=381930/mana-spring-totem" target="blank">Mana Spring</a>

natures_fury: <a href="https://www.wowhead.com/spell=381655/natures-fury" target="blank">Nature's Fury</a>

natures_guardian: <a href="https://www.wowhead.com/spell=30884" target="blank">Nature's Guardian</a>

natures_swiftness: <a href="https://www.wowhead.com/spell=378081/natures-swiftness" target="blank">Nature's Swiftness</a>
ns: <a href="https://www.wowhead.com/spell=378081/natures-swiftness" target="blank">Nature's Swiftness</a>

planes_traveler: <a href="https://www.wowhead.com/spell=381647/planes-traveler" target="blank">Planes Traveler</a>

poison_cleansing_totem: <a href="https://www.wowhead.com/spell=383013/poison-cleansing-totem" target="blank">Poison Cleansing Totem</a>
pct: <a href="https://www.wowhead.com/spell=383013/poison-cleansing-totem" target="blank">Poison Cleansing Totem</a>

purge: <a href="https://www.wowhead.com/spell=370" target="blank">Purge</a>

spirit_wolf: <a href="https://www.wowhead.com/spell=260878" target="blank">Spirit Wolf</a>
sw: <a href="https://www.wowhead.com/spell=260878" target="blank">Spirit Wolf</a>

static_charge: <a href="https://www.wowhead.com/spell=265046" target="blank">Static Charge</a>

spirit_walk: <a href="https://www.wowhead.com/spell=58875/spirit-walk" target="blank">Spirit Walk</a>

spiritwalkers_aegis: <a href="https://www.wowhead.com/spell=378077/spiritwalkers-aegis" target="blank">Spiritwalker's Aegis</a>

spiritwalkers_grace: <a href="https://www.wowhead.com/spell=79206" target="blank">Spiritwalker's Grace</a>
swg: <a href="https://www.wowhead.com/spell=79206" target="blank">Spiritwalker's Grace</a>

stoneskin_totem: <a href="https://www.wowhead.com/spell=383017/stoneskin-totem" target="blank">Stoneskin Totem</a>

surging_shields: <a href="https://www.wowhead.com/spell=382033/surging-shields" target="blank">Surging Shields</a>

swirling_currents: <a href="https://www.wowhead.com/spell=378094/swirling-currents" target="blank">Swirling Currents</a>

thunderous_paws: <a href="https://www.wowhead.com/spell=378075/thunderous-paws" target="blank">Thunderous Paws</a>

thundershock: <a href="https://www.wowhead.com/spell=378779/thundershock" target="blank">Thundershock</a>

thunderstorm: <a href="https://www.wowhead.com/spell=51490" target="blank">Thunderstorm</a>

totemic_focus: <a href="https://www.wowhead.com/spell=382201/totemic-focus" target="blank">Totemic Focus</a>

totemic_projection: <a href="https://www.wowhead.com/spell=108287/totemic-projection" target="blank">Totemic Projection</a>

totemic_recall: <a href="https://www.wowhead.com/spell=108285/totemic-recall" target="blank">Totemic Recall</a>

totemic_surge: <a href="https://www.wowhead.com/spell=381867/totemic-surge" target="blank">Totemic Surge</a>

tranquil_air_totem: <a href="https://www.wowhead.com/spell=383019/tranquil-air-totem" target="blank">Tranquil Air Totem</a>

tremor_totem: <a href="https://www.wowhead.com/spell=8143" target="blank">Tremor Totem</a>

voodoo_mastery: <a href="https://www.wowhead.com/spell=204268/voodoo-mastery" target="blank">Voodoo Mastery</a>

wind_rush_totem: <a href="https://www.wowhead.com/spell=192077" target="blank">Wind Rush Totem</a>
wrt: <a href="https://www.wowhead.com/spell=192077" target="blank">Wind Rush Totem</a>

winds_of_alakir: <a href="https://www.wowhead.com/spell=382215/winds-of-alakir" target="blank">Winds of Al'Alkir</a>

# PvP
burrow: <a href="https://www.wowhead.com/ptr/spell=409293/burrow" target="blank">Burrow</a>

control_of_lava: <a href="https://www.wowhead.com/spell=204393" target="blank">Control of Lava</a>
col: <a href="https://www.wowhead.com/spell=204393" target="blank">Control of Lava</a>

counterstrike_totem: <a href="https://www.wowhead.com/spell=204331" target="blank">Counterstrike Totem</a>

grounding_totem: <a href="https://www.wowhead.com/spell=204336" target="blank">Grounding Totem</a>

precognition: <a href="https://www.wowhead.com/spell=377360/precognition" target="blank">Precognition</a>

seasoned_winds: <a href="https://www.wowhead.com/spell=355630/seasoned-winds" target="blank">Seasoned Winds</a>

skyfury_totem: <a href="https://www.wowhead.com/spell=204330" target="blank">Skyfury Totem</a>

spectral_recovery: <a href="https://www.wowhead.com/spell=204261" target="blank">Spectral Recovery</a>

static_field_totem: <a href="https://www.wowhead.com/spell=355580/static-field-totem" target="blank">Static Field Totem</a>

swelling_waves: <a href="https://www.wowhead.com/spell=204264" target="blank">Swelling Waves</a>

tidebringer: <a href="https://www.wowhead.com/spell=236501/tidebringer" target="blank">Tidebringer</a>

traveling_storms: <a href="https://www.wowhead.com/spell=204403" target="blank">Traveling Storms</a>

unleash_shield: <a href="https://www.wowhead.com/spell=356736/unleash-shield" target="blank">Unleash Shield</a>

volcanic_surge: <a href="https://www.wowhead.com/ptr/spell=408572/volcanic-surge" target="blank">Volcanic Surge</a>
